// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKhYqLBNvNPqsJRbsZPctggzrD3uFZaa0',
    appId: '1:273442439217:web:5b9e08e4df9df9a4bcd510',
    messagingSenderId: '273442439217',
    projectId: 'bytesized-f1578',
    authDomain: 'bytesized-f1578.firebaseapp.com',
    storageBucket: 'bytesized-f1578.firebasestorage.app',
    measurementId: 'G-K4LC38745T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO5J7uxEWnvuSTsfQC2U1pBt1LTcFFrAI',
    appId: '1:273442439217:android:2be71a1f4149f357bcd510',
    messagingSenderId: '273442439217',
    projectId: 'bytesized-f1578',
    storageBucket: 'bytesized-f1578.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDChC6Dyy0qpnJTWNDv3vyAMf4zPRxkCfk',
    appId: '1:273442439217:ios:d754baa259858dddbcd510',
    messagingSenderId: '273442439217',
    projectId: 'bytesized-f1578',
    storageBucket: 'bytesized-f1578.firebasestorage.app',
    iosBundleId: 'com.example.bytesized',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDChC6Dyy0qpnJTWNDv3vyAMf4zPRxkCfk',
    appId: '1:273442439217:ios:d754baa259858dddbcd510',
    messagingSenderId: '273442439217',
    projectId: 'bytesized-f1578',
    storageBucket: 'bytesized-f1578.firebasestorage.app',
    iosBundleId: 'com.example.bytesized',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKhYqLBNvNPqsJRbsZPctggzrD3uFZaa0',
    appId: '1:273442439217:web:5c5eda13acfbe1aabcd510',
    messagingSenderId: '273442439217',
    projectId: 'bytesized-f1578',
    authDomain: 'bytesized-f1578.firebaseapp.com',
    storageBucket: 'bytesized-f1578.firebasestorage.app',
    measurementId: 'G-M2TNXYV3QH',
  );
}
